//
// Created by Allen on 2021/8/1.
//

#ifndef HEAD_FIRST_DESIGN_PARTTERN_NYSTYLEPEPPERONIPIZZA_H
#define HEAD_FIRST_DESIGN_PARTTERN_NYSTYLEPEPPERONIPIZZA_H

#include "Pizza.h"
class NYStylePepperoniPizza : public Pizza {

};


#endif //HEAD_FIRST_DESIGN_PARTTERN_NYSTYLEPEPPERONIPIZZA_H
